version: '3.8'

services:
  example-a:
    build: ./SAUP-example-a-svc
    depends_on:
      - kafka
      - db
    env_file:
      - ./SAUP-example-a-svc/.env
    ports:
      - "5001:5000"
    networks:
      - saup-network

  example-b:
    build: ./SAUP-example-b-svc
    depends_on:
      - kafka
      - db
    env_file:
      - ./SAUP-example-b-svc/.env
    ports:
      - "5002:5000"
    networks:
      - saup-network

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: saup123
    volumes:
      - ./volumes/mysql:/var/lib/mysql  
    healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p$saup123"]
          interval: 5s
          timeout: 3s
          retries: 10
    networks:
      - saup-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./volumes/kafka/data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - saup-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - saup-network

networks:
  saup-network:
    driver: bridge